// Writes src/mock/manifest.generated.ts: a listing of real Minv project files so the
// preview fixture can browse and search actual source text served over localhost.
import { readdirSync, statSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const renderer = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const project = path.resolve(renderer, '../..');
const include = ['src', 'test', 'scripts', 'docs', 'themes', 'media', 'desktop/renderer/src', 'desktop/renderer/styles', 'desktop/renderer/scripts'];
const top = ['package.json', 'tsconfig.json', 'LICENSE', 'MINV_PRD.md', 'README.md', '.gitignore'];
const skip = new Set(['node_modules', 'dist', '.upstream', 'benchmarks', 'mock']);
const tree = {};
const add = (dir, entry) => (tree[dir] ??= []).push(entry);

function walk(rel) {
  const abs = path.join(project, rel);
  for (const name of readdirSync(abs).sort()) {
    if (skip.has(name) || name.endsWith('.generated.ts')) continue;
    const child = rel ? `${rel}/${name}` : name;
    const info = statSync(path.join(abs, name));
    if (info.isDirectory()) { add(rel, { name, kind: 'directory' }); walk(child); }
    else add(rel, { name, kind: 'file', size: info.size });
  }
}
for (const name of top) { try { add('', { name, kind: 'file', size: statSync(path.join(project, name)).size }); } catch {} }
for (const dir of include.filter(d => { try { return statSync(path.join(project, d)).isDirectory(); } catch { return false; } })) {
  const parts = dir.split('/');
  for (let i = 0; i < parts.length; i++) {
    const parent = parts.slice(0, i).join('/');
    if (!(tree[parent] ?? []).some(e => e.name === parts[i])) add(parent, { name: parts[i], kind: 'directory' });
  }
  walk(dir);
}
for (const list of Object.values(tree)) list.sort((a, b) => (a.kind === 'directory' ? 0 : 1) - (b.kind === 'directory' ? 0 : 1) || a.name.localeCompare(b.name));
mkdirSync(path.join(renderer, 'src/mock'), { recursive: true });
writeFileSync(path.join(renderer, 'src/mock/manifest.generated.ts'), `// Generated by scripts/fixture.mjs. Preview fixture only.\nimport type { DirectoryEntry } from '../contract.js';\nexport const MINV_TREE: Record<string, DirectoryEntry[]> = ${JSON.stringify(tree)};\n`);
console.log(`fixture: ${Object.values(tree).flat().filter(e => e.kind === 'file').length} files listed`);
